### ISSUE TITLE
No "stage2" after `./x.py build`

### ISSUE THREAD

**Issue by tobymurray** [MabezDev/xtensa-rust-quickstart#26]
I believe I'm following the instructions. What I've done so far:

```
$ git clone https://github.com/MabezDev/rust-xtensa
$ cd rust-xtensa
$ ./configure --experimental-targets=Xtensa
$ ./x.py build
```

That all appears to have worked. The next step says to set the environment variable: `RUSTC=/path/to/rust-xtensa/build/x86_64-unknown-linux-gnu/stage2/bin/rustc`

Looking in my `/path/to/rust-xtensa/build/x86_64-unknown-linux-gnu/` I have the following:

```
llvm
stage0
stage0-rustc
stage0-std
stage0-sysroot
stage0-tools
stage1
stage1-std
```

Notably absent is "stage2". Have I done something wrong? I'm on Ubuntu 18.04.5 LTS and I'm on `435fc68` in [rust-xtensa](https://github.com/MabezDev/rust-xtensa). My build completed in a way that seems reasonable (e.g. didn't explode):
```
   ... <SNIP> ...
   Compiling rustdoc v0.0.0 (/home/toby/git/esp32/rust-xtensa/src/librustdoc)
   Compiling rustdoc-tool v0.0.0 (/home/toby/git/esp32/rust-xtensa/src/tools/rustdoc)
   Finished release [optimized] target(s) in 1m 21s
   Build completed successfully in 0:18:27
```

**Comment by tobymurray** [comment]
Advised on [matrix](https://matrix.to/#/!LdaNPfUfvefOLewEIM:matrix.org/$Lidfy63Zq-cX1YHmJmXO6MUWAZPSRQnhZPC0gk0zs6I?via=matrix.org&via=icewind.nl) to run `./x.py install` after. Is this expected to be required? Maybe a missing step in the instructions.

Looking at the current Rust [README](https://github.com/rust-lang/rust/blob/master/README.md) it says:
>Build and install:

>`./x.py build && ./x.py install`

**Comment by tobymurray** [comment]
Following https://github.com/rust-lang/rust/issues/40108#issuecomment-368269981 I made it through the build, so I'll try continuing.

**Comment by MabezDev** [comment]
Hmm, it seems the compiler build system has changed a bit. I'll dig into it and report back. 

FYI I use `./x.py dist` which essentially builds everything, this is probably overkill for most people.

**Comment by tobymurray** [comment]
I'm not sure why, as it seems to be "resolved" in the Rust world, but I ran into the same issues described in the linked ticket:

```
touch: cannot touch '/usr/local/lib/rust-install-probe': Permission denied
install: error: can't write to destination. consider `sudo`.
```

>     Go to Rust source directory
>     Rename config.toml.example to config.toml
>     In config.toml, in section install set entry prefix = "~/.rustup/toolchains/dev"
>     Run ./x.py build && ./x.py install
>     Run rustup default dev

Except I used an absolute path, because `~` was not interpreted as "home", but as literally the `~` character (so it created a folder named `~`). I'm currently at the point where it seems to be working, I've installed `cargo-espflash` and next up is flashing something.

**Comment by cormacrelf** [comment]
```
./x.py build
# this probably does stage 1 as well, I think
./x.py build --stage 2
rustup toolchain link xtensa build/my-target-triple/stage2
cd ....
rustup override set xtensa
```

**Comment by eugenio** [comment]
the documentation on the github landing page still reports the 

`./x.py build ` instead of  `./x.py build  --stage 2`

for windows build.

Can it be corrected?
