### ISSUE TITLE
Which commit of llvm-xtensa to use?

### ISSUE THREAD

**Issue by bjoernQ** [MabezDev/xtensa-rust-quickstart#3]
I got it working yesterday so far but today I pulled latest changes from llvm-xtensa. They added e.g support for esp8266 - however now I am not able to compile libcore anymore.

So the quick question: which commit should I pick and do you also have problems with the latest changes in llvm-xtensa?

**Comment by lexxvir** [comment]
Hi @bjoernQ.

I also have problems to compile code with current HEAD of llvm-xtensa. Now I'm using https://github.com/espressif/llvm-xtensa/commit/bdf572d51d94de5590531c0eee320f7c99c96292, it compiles fine.

**Comment by bjoernQ** [comment]
Thanks @lexxvir,

would be nice to get head working since it could mean to potentially also target esp8266 but at least I now have a working commit hash - I'll check out that commit and from now on be carefully about pulling changes in llvm-xtensa

Thanks!

**Comment by bjoernQ** [comment]
I think I got llvm-xtensa head working with Rust - all it needs is `cpu: "esp32".to_string(),` added to the options in `xtensa-none-elf.rs`

Hope this helps and works for you

**Comment by MabezDev** [comment]
thanks @bjoernQ, I didn't realise espressif have added support for the esp8266 so soon! 

I'll add two new targets, `xtensa-esp32-none-elf`,  `xtensa-esp8266-none-elf` and then remove `xtensa-none-elf` as soon as possible.

**Comment by MabezDev** [comment]
Hey guys, it has been a while, apologies but I've been super busy. 

The changes I suggested have been added in https://github.com/MabezDev/rust-xtensa/commit/ad570c5cb999f62a03156286fdb5d3d1bbd0fb8b, which from my testing now uses the espressif master.

It looks like espressif have started to add object generation to thier fork so I will be playing with that soon.

**Comment by bjoernQ** [comment]
Thanks - that's great. Looking forward seeing object generation added to their backend - I have a private branch of Rust with some hacks I really want to get rid of once we have object generation in place

**Comment by bjoernQ** [comment]
Tried the latest version with the current head of the llvm backend but building core fails:

```
  process didn't exit successfully: `D:\rust_xtensa\rust\build\x86_64-pc-windows-msvc\stage2\bin\rustc --crate-name core D:\rust_xtensa\rust\src\libcore\lib.rs --color always --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C panic=abort -C codegen-units=1 -C metadata=24d0b39b385d2852 -C extra-filename=-24d0b39b385d2852 --out-dir C:\Users\bjoern\AppData\Local\Temp\xargo.ldadfFkBvdVm\target\xtensa-esp32-none-elf\release\deps --target xtensa-esp32-none-elf -L dependency=C:\Users\bjoern\AppData\Local\Temp\xargo.ldadfFkBvdVm\target\xtensa-esp32-none-elf\release\deps -L dependency=C:\Users\bjoern\AppData\Local\Temp\xargo.ldadfFkBvdVm\target\release\deps -C save-temps -C link-arg=-nostdlib -C link-arg=-Tesp32.ld -C link-arg=-ucall_user_start_cpu0 -C link-arg=-u__cxa_guard_dummy -C link-arg=-u__cxx_fatal_exception -C link-arg=-uld_include_panic_highint_hdl -C link-arg=-uesp_app_desc -C link-arg=-Wl,--gc-sections -C link-arg=-Wl,-static -C link-arg=-Wl,--start-group -C link-arg=-Trom.ld -C link-arg=-lgcc -C link-arg=-lstdc++ -C link-arg=-lgcov -C link-arg=-Wl,--end-group -C link-arg=-Wl,-EL --sysroot C:\Users\bjoern\.xargo -Z force-unstable-if-unmarked` (exit code: 0x80000003)
error: `"cargo" "build" "--release" "--manifest-path" "C:\\Users\\bjoern\\AppData\\Local\\Temp\\xargo.ldadfFkBvdVm\\Cargo.toml" "--target" "xtensa-esp32-none-elf" "-v" "-p" "core"` failed with exit code: Some(101)
```

Any idea what could be the cause or what exit code 0x80000003 could mean?
Any idea how I could debug it on my own?

**Comment by pantsman0** [comment]
It looks like you're running windows. Error code 0x80000003  looks like it's a windows error code - you get 0x80000003  when there's a double fault in exception handling.

If you're getting it in rustc, the source would probably be something like a panic occuring inside a panic handler.

**Comment by MabezDev** [comment]
Closing as the default way to build this fork has changed. See https://github.com/MabezDev/rust-xtensa#using-this-fork
