### ISSUE TITLE
optimize clone instructions in readme

### ISSUE THREAD

**Issue by BartMassey** [MabezDev/xtensa-rust-quickstart#41]
Might want to modify the README to suggest `git clone --depth 1 --recursive --shallow-submodules`? Decreases the clone time and size considerably due to not importing the history of LLVM, looks like, and should be adequate for most folks' uses.

**Comment by MabezDev** [comment]
Sure! Would you mind submitting a PR?

**Comment by BartMassey** [comment]
submitted PR #42.
