### ISSUE TITLE
LLVM ERROR: Error while trying to spill A2 from class AR: 

### ISSUE THREAD

**Issue by eugenio** [MabezDev/xtensa-rust-quickstart#43]
I tried to build the sample project but got this error:

```
LLVM ERROR: Error while trying to spill A2 from class AR: Cannot scavenge register without an emergency spill slot!
error: could not compile `core`
```
Anybody knows how to solve this?

```
PS C:\Users\eugen\OneDrive\Documenti\programmazione\rust\xtensa-rust-quickstart> cargo build -Z build-std --features="xtensa-lx-rt/lx6,xtensa-lx/lx6,esp32-hal"
   Compiling core v0.0.0 (D:\rust-xtensa\build\x86_64-pc-windows-msvc\stage2\lib\rustlib\src\rust\library\core)
   Compiling xtensa-lx v0.3.0
   Compiling ident_case v1.0.1
   Compiling strsim v0.9.3
   Compiling fnv v1.0.7
   Compiling xtensa-lx-rt v0.5.0
   Compiling esp32 v0.10.0
   Compiling esp32-hal v0.2.0
   Compiling unwind v0.0.0 (D:\rust-xtensa\build\x86_64-pc-windows-msvc\stage2\lib\rustlib\src\rust\library\unwind)
   Compiling quote v1.0.9
   Compiling bare-metal v0.2.5
   Compiling syn v1.0.72
   Compiling darling_core v0.10.2
   Compiling xtensa-lx-rt-proc-macros v0.1.0
   Compiling darling_macro v0.10.2
   Compiling darling v0.10.2
   Compiling esp32-hal-proc-macros v0.2.0
   Compiling rustc-std-workspace-core v1.99.0 (D:\rust-xtensa\build\x86_64-pc-windows-msvc\stage2\lib\rustlib\src\rust\library\rustc-std-workspace-core)
   Compiling compiler_builtins v0.1.39
   Compiling libc v0.2.85
LLVM ERROR: Error while trying to spill A2 from class AR: Cannot scavenge register without an emergency spill slot!
error: could not compile `core`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
LLVM ERROR: Error while trying to spill A9 from class AR: Cannot scavenge register without an emergency spill slot!
error: build failed
```

**Comment by MabezDev** [comment]
I believe this to be an upstream llvm issue, you can try using some of the fixes in this issue: https://github.com/espressif/llvm-project/issues/13

**Comment by brookman** [comment]
I ran into the same problem (even with the latest rust-build) but found a workaround by setting `lto = false` (see: [here](https://github.com/espressif/llvm-project/issues/13#issuecomment-579050474)).
My Cargo.toml:

`[profile.release]
lto = false`

Then build with --release:
`cargo.exe build --release  --package my_project --bin my_project `

**Comment by JeanBlignaut** [comment]
`xtensa-rust-quickstart git:(master) ✗ cargo espflash --example esp8266 --features="xtensa-lx-rt/lx106 xtensa-lx/lx106 esp8266-hal" /dev/tty.usbserial-016E3EFD
Serial port: /dev/tty.usbserial-016E3EFD
Connecting...

   Compiling compiler_builtins v0.1.49
   Compiling darling_macro v0.10.2
   Compiling alloc v0.0.0 (/Users/oneiric/.rustup/toolchains/esp/lib/rustlib/src/rust/library/alloc)
LLVM ERROR: Error while trying to spill A12 from class AR: Cannot scavenge register without an emergency spill slot!
error: could not compile `compiler_builtins`
warning: build failed, waiting for other jobs to finish...
error: build failed`

my rust version is 1.57.0-dev

**Comment by JeanBlignaut** [comment]
BTW I also get an error when I add --chip ESP8266 as per the readme

**Comment by MabezDev** [comment]
This has now been fixed internally in our LLVM fork. I am commenting here as this repo is about to be archived. Please keep an eye out for the 1.60.0.1 release of our custom Rust compiler which will include this fix.
