### ISSUE TITLE
Error running cargo metadata

### ISSUE THREAD

**Issue by aghoneim92** [MabezDev/xtensa-rust-quickstart#49]
I'm experiencing this error on vscode with rust-analyzer:
`cargo metadata` exited with an error: error: invalid configuration for key `target.runner` expected a table, but found a string for `target.runner`.cargo/config

**Comment by MabezDev** [comment]
Thanks for your issue! This repo is now obsolete, there is now a quickstart repo for [bare-metal](https://github.com/esp-rs/esp-template) and a template for [using the standard library](https://github.com/esp-rs/esp-idf-template).
