### ISSUE TITLE
Add better starting instructions

### ISSUE THREAD

**Issue by skorokithakis** [MabezDev/xtensa-rust-quickstart#6]
There are some instructions currently in the README, but I'm not sure how to do any of the things they mention:

> Update setenv to use your xtensa enabled rustc, then simply run source setenv. From then on, you can just call xargo build or use the built in flash script to build and flash to the esp.

It would be great if the instructions were spelled out in full (i.e. with full commands), and perhaps a sample project added, showing how to flip a few GPIOs or whatnot. I think that would be much more helpful in getting newbies started.

**Comment by MabezDev** [comment]
Thanks, this is some well needed feedback.

> I'm not sure how to do any of the things they mention

Yeah these are mainly notes to myself in the form of 'documentation', I will definitely look at rewriting both the xtensa-quickstart and rust-xtensa readme's.

> perhaps a sample project added, showing how to flip a few GPIOs or whatnot

So I guess its not clear, but that is this project

> I think that would be much more helpful in getting newbies started

Unforntunately I don't think this is quite ready for newbies as it required building rust itself, specifically [my fork with the esp changes in it](https://github.com/MabezDev/rust-xtensa) which isn't  too hard but far from ideal. I am looking into distributing prebuilt binaries to help with that.

**Comment by skorokithakis** [comment]
> I will definitely look at rewriting both the xtensa-quickstart and rust-xtensa readme's.

That'd be great, thanks! I can't wait to try it out.

> So I guess its not clear, but that is this project

Oh, sorry, I guess I looked at another one and not this one, maybe? I did look at one that was boilerplate and not an example, but you are correct that this project is a good example. Now I'm even more excited to try it out.

> Unforntunately I don't think this is quite ready for newbies as it required building rust itself

I don't really mind building stuff, I can probably figure it out easily enough. I know this isn't very helpful, but what I find difficult is compiling firmware/flashing, the rest I can deal with. I think the documentation for this project should focus on what's unique about it, as that's the part I can't find info on anywhere else. I can probably find out how to build Rust from various resources (though, obviously, if your Rust fork needs something specific, that should be noted in its readme).

Thanks for your help!

**Comment by samsieber** [comment]
I came across an article - someone created a docker image with a compiled copy of your llvm fork:  https://dev.to/mtnmts/containerized-builds-for-rust-on-the-esp32-e8m

**Comment by MabezDev** [comment]
This has been an ongoing process, but I'd like to think the instructions are much easier to follow now.

In particular, its gotten considerably easier to build the entire toolchain with https://github.com/MabezDev/xtensa-rust-quickstart#recommended-build-method

I will close this now, but feel free to follow up if you feel its still not at good as it should be!
