### ISSUE TITLE
LLVM error: Can't create a MachineFunction using a Module with a Target-incompatible DataLayout attached

### ISSUE THREAD

**Issue by Gasper** [MabezDev/xtensa-rust-quickstart#9]
When building the project for the first time using `xargo`, it first tries to build `core` library, but fails with the following error:
```
   Compiling core v0.0.0 (/home/esp/esp/esp-rust/rust-xtensa/src/libcore)
rustc: ../lib/CodeGen/MachineFunction.cpp:200: void llvm::MachineFunction::init(): Assertion `Target.isCompatibleDataLayout(getDataLayout()) && "Can't create a MachineFunction using a Module with a " "Target-incompatible DataLayout attached\n"' failed.
error: could not compile `core`.

Caused by:
  process didn't exit successfully: `/home/esp/esp/esp-rust/rust-xtensa/build/x86_64-unknown-linux-gnu/stage2/bin/rustc --edition=2018 --crate-name core /home/esp/esp/esp-rust/rust-xtensa/src/libcore/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C codegen-units=1 -C metadata=298fb4c6de191102 -C extra-filename=-298fb4c6de191102 --out-dir /tmp/xargo.jZvFVALbTwu7/target/xtensa-esp32-none-elf/release/deps --target xtensa-esp32-none-elf -L dependency=/tmp/xargo.jZvFVALbTwu7/target/xtensa-esp32-none-elf/release/deps -L dependency=/tmp/xargo.jZvFVALbTwu7/target/release/deps -C link-arg=-nostartfiles -C debuginfo=0 -C link-arg=-Wl,-Tlink.x --emit llvm-bc,link --sysroot /home/esp/.xargo -Z force-unstable-if-unmarked` (signal: 6, SIGABRT: process abort signal)
error: `"cargo" "build" "--release" "--manifest-path" "/tmp/xargo.jZvFVALbTwu7/Cargo.toml" "--target" "xtensa-esp32-none-elf" "-p" "core"` failed with exit code: Some(101)
   0: error_chain::make_backtrace
   1: <error_chain::State as core::default::Default>::default
   2: <std::process::Command as xargo::extensions::CommandExt>::run
   3: xargo::sysroot::build
   4: xargo::sysroot::update
   5: xargo::main_inner
   6: std::rt::lang_start::{{closure}}
   7: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
      std::panicking::try::do_call
             at src/libstd/panicking.rs:292
   8: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
   9: std::panicking::try
             at src/libstd/panicking.rs:270
      std::panic::catch_unwind
             at src/libstd/panic.rs:394
      std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  10: main
  11: __libc_start_main
  12: _start
```

### Probable cause
This seems to be caused by data layout different between `espressif/llvm-project` and `MabezDev/rust-xtensa` projects:
**espressif/llvm-project:** [e-m:e-p:32:32-i8:8:32-i16:16:32-i64:64-n32](https://github.com/espressif/llvm-project/blob/xtensa_release_9.0.1/llvm/lib/Target/Xtensa/XtensaTargetMachine.cpp#L34)
**MabezDev/rust-xtensa:** [e-m:e-p:32:32-i1:8:32-i8:8:32-i16:16:32-i64:64-f64:64-a:0:32-n32](https://github.com/MabezDev/rust-xtensa/blob/xtensa-target/src/librustc_target/spec/xtensa_esp32_none_elf.rs#L10)

### Workaround
If either code is modified so that layout matches the other (I modified the LLVM), the problem disappears.

### Versions used
I used the latest default branches for both of the projects:
**espressif/llvm-project:** xtensa_release_9.0.1 / 654ba115e556 (Feb 5, 2020)
**MabezDev/rust-xtensa:** xtensa-target / 2d3ec14f5877(Feb 4, 2020)

### May be related
May be related to the issue bjoernQ was asking about here: https://github.com/MabezDev/xtensa-rust-quickstart/issues/3#issuecomment-502353608

**Comment by MabezDev** [comment]
Thanks for the report!

> Probable cause
This seems to be caused by data layout different between espressif/llvm-project and MabezDev/rust-xtensa projects

Correct as I ran into this issue too. https://github.com/MabezDev/rust-xtensa/pull/22 has the fixed data layout string, that should fix your issue.

**Comment by Gasper** [comment]
Awesome!
Using `built-in-llvm` (548213793ce91714) branch on MabezDev/rust-xtensa and `xtensa_release_9.0.1_with_rust_patches` (1ad7aa125beddf) on MabezDev/llvm-project fixes the problem.
